[package]
name = "pymemprofile_api"
version = "0.1.0"
authors = ["Itamar Turner-Trauring <itamar@pythonspeed.com>"]
edition = "2018"
license = "Apache 2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "14.2.0"
itertools = "0.8.2"
ahash = "0.6.3"
derivative = "2.1.1"
lazy_static = "1.4.0"

[target.'cfg(target_os = "linux")'.dependencies.cgroups-rs]
version = "0.2.0"

[dependencies.inferno]
version = "0.9.9"
default-features = false

[dependencies.psutil]
version = "3.2.0"
default-features = false
features = ["memory", "process"]

[dev-dependencies]
proptest = "0.9.5"

[lib]
name = "pymemprofile_api"

[features]
default = []

# Tweaks for the production version of Fil.
production = []
